In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

C:\Users\ashut\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [ ]:
df=pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
x=df.iloc[:,:-1]
y=df[['Outcome']]

In [ ]:
x,y

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0              6      148             72             35        0  33.6   
 1              1       85             66             29        0  26.6   
 2              8      183             64              0        0  23.3   
 3              1       89             66             23       94  28.1   
 4              0      137             40             35      168  43.1   
 ..           ...      ...            ...            ...      ...   ...   
 763           10      101             76             48      180  32.9   
 764            2      122             70             27        0  36.8   
 765            5      121             72             23      112  26.2   
 766            1      126             60              0        0  30.1   
 767            1       93             70             31        0  30.4   
 
      DiabetesPedigreeFunction  Age  
 0                       0.627   50  
 1                    

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
x,y, test_size=0.30)

In [ ]:
from sklearn.svm import SVC

In [ ]:
# for classified data
model = SVC()

In [ ]:
model.fit(x_train,y_train)

C:\Users\ashut\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [ ]:
pred=model.predict(x_test)

In [ ]:
pred

array([-0.05211088,  0.58350343,  0.71301319,  0.6209072 ,  0.05320391,
        0.247294  ,  0.01668426,  0.64193434,  0.71595273,  0.00257833,
        0.05536896,  0.74265813,  0.1087239 ,  0.16187713,  0.36372457,
        0.03508607,  0.46390362,  0.0450885 ,  0.3259439 ,  0.11339444,
        0.71449441,  0.58295445, -0.00617439,  0.01751054,  0.31123294,
        0.33685476,  0.18263148,  0.22942035,  0.73283224,  0.34391236,
        0.39618832,  0.29151783,  0.58234548,  0.69404724,  0.15201336,
       -0.04159607,  0.80214424,  0.11573964,  0.21454543,  0.31586434,
        0.15531962,  0.67968909,  0.94461411,  0.4214083 ,  0.266866  ,
        0.00864468,  0.70236708,  0.27819876, -0.1421385 ,  0.3401018 ,
       -0.03245187,  0.52915822,  0.71735789,  0.79577967,  0.28759951,
        0.28995173,  0.11293091, -0.06844302,  0.46501609,  0.58392319,
        0.34944358,  0.58442211,  0.17567287, -0.03525735,  0.19298205,
       -0.07663923,  0.34654617,  0.42857216,  0.71073568,  0.23

In [ ]:
accuracy_score(y_test,pred)

0.7359307359307359

In [ ]:
from sklearn.metrics import  confusion_matrix
confusion_matrix(y_test,pred)

array([[131,  24],
       [ 37,  39]], dtype=int64)

In [ ]:
model.support_vectors_

array([[2.00e+00, 1.29e+02, 7.40e+01, ..., 3.32e+01, 5.91e-01, 2.50e+01],
       [1.00e+01, 1.79e+02, 7.00e+01, ..., 3.51e+01, 2.00e-01, 3.70e+01],
       [0.00e+00, 1.07e+02, 7.60e+01, ..., 4.53e+01, 6.86e-01, 2.40e+01],
       ...,
       [4.00e+00, 1.56e+02, 7.50e+01, ..., 4.83e+01, 2.38e-01, 3.20e+01],
       [5.00e+00, 1.30e+02, 8.20e+01, ..., 3.91e+01, 9.56e-01, 3.70e+01],
       [2.00e+00, 1.02e+02, 8.60e+01, ..., 4.55e+01, 1.27e-01, 2.30e+01]])