# Shape of an Array
The shape of an array is the number of elements in each dimension.

# Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

# 1D

In [5]:
import numpy as np
arr1d = np.array([1,2,3,4,5])
print(arr1d.shape)

(5,)


# 2D

In [6]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d.shape)

(2, 4)


# 3D

In [8]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
