# NumPy Creating Arrays


# Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr = np.array((1,2,3))
print(arr)

[1 2 3]


# Dimensions in Arrays


# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [8]:
arr = np.array(45)
print(arr)

45


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:
one_d_array =np.array([1,3,4,56])
print(one_d_array)

[ 1  3  4 56]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [11]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

# Example
Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [16]:
a = np.array(10)
b = np.array([1,2,3,4,5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
